import Image from 'next/image'
import Nav1 from "../components/Nav1";
import Head from "next/head";
import Cardsection from '../components/Cardsection';
import { products } from '../../data'

export default function Home() {
  return (
    <>
      <Head>
        <title>Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/robot.jpg" />
        <link href="/dist/output.css" rel="stylesheet" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>

      <div>
        <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">New Releases</h2>

          <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
            {products.map((product) => {
              return (
                <Cardsection key={product.id} {...product} />
              )




            })}
          </div>
        </div>

      </div>



    </>

  )
}
