import Image from 'next/image'
import Nav1 from "../components/Nav1";
import Head from "next/head";
import Cardsection from '../components/Cardsection';
import Songsection from '@/components/songsection';
// import { products } from '../../data'
import Link from 'next/link'
import Artists from '@/components/Artists'




const artists = []
const finalartists = []


function handleartists(bigarray) {
  var authorname = ''
  bigarray.forEach(element => {
    if (element.author !== authorname) {
      authorname = element.author
      if (!finalartists.includes(authorname)) {
        finalartists.push(authorname)
        artists.push(element)
      }
    }
  });
  return artists;
}


export default function Home({ products, songs }) {
  const designproducts = products.filter((product) => product.category === "Design")
  const designdevproducts = products.filter((product) => product.category === "Design and Dev")
  const businessproducts = products.filter((product) => product.category === "Business")
  const lifestyleproducts = products.filter((product) => product.category === "Lifestyle")
  const developproducts = products.filter((product) => product.category === "Development")
  handleartists(songs)




  return (
    <>
      <Head>
        <title>Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
        <link href="/dist/output.css" rel="stylesheet" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <Nav1 />

      <div>
        <div className="mx-auto max-w-2xl px-10 py-10 sm:px-6 sm:py-16 lg:max-w-7xl lg:px-8 container">
          <div>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Songs</h2>
              <Link href='/music' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>
            <div className="mt-6 mx-auto grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {songs.slice(0, 4).map((song) => {
                return (
                  <Songsection key={song.id} {...song} />
                )
              })}
            </div>
          </div>
          <div className='my-20'>
            <div className="mx-auto max-w-2xl px-10 py-10 sm:px-6 sm:py-16 lg:max-w-7xl lg:px-8 ">
              <div className='flex justify-between items-center'>
                <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Top artists</h2>
                <Link href='/music#artists' className='hover:underline hover:underline-offset-4'>

                  View All


                </Link>
              </div>
              <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-5 xl:gap-x-8 mx-auto">
                {artists.slice(0, 5).map((artist) => {
                  return (
                    <Artists key={artist.id} {...artist} />
                  )
                })}
              </div>
            </div>
          </div>
          <div className='my-20'>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Design</h2>
              <Link href='/design' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>
            <div className="mt-6 mx-auto grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {designproducts.slice(0, 4).map((product) => {
                return (
                  <Cardsection key={product.id} {...product} />
                )
              })}
            </div>
          </div>
          <div className='my-20'>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Development</h2>
              <Link href='/development' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>

            <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {developproducts.slice(0, 4).map((product) => {
                return (
                  <Cardsection key={product.id} {...product} />
                )
              })}
            </div>
          </div>
          <div className='my-20'>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Design & Dev</h2>
              <Link href='/designDev' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>
            <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {designdevproducts.slice(0, 4).map((product) => {
                return (
                  <Cardsection key={product.id} {...product} />
                )
              })}
            </div>
          </div>
          <div className='my-20'>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Business</h2>
              <Link href='/business' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>
            <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {businessproducts.slice(0, 4).map((product) => {
                return (
                  <Cardsection key={product.id} {...product} />
                )
              })}
            </div>
          </div>
          <div className='my-20'>
            <div className='flex justify-between items-center'>
              <h2 className="text-2xl font-bold tracking-tight text-gray-900  ">Lifestyle</h2>
              <Link href='/lifestyle' className='hover:underline hover:underline-offset-4'>View All</Link>
            </div>

            <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {lifestyleproducts.slice(0, 4).map((product) => {
                return (
                  <Cardsection key={product.id} {...product} />
                )
              })}
            </div>
          </div>



        </div>

      </div>



    </>

  )
}


export async function getStaticProps() {
  const res = await fetch('https://newpodcast2.vercel.app/api/products');
  const songs = await fetch('https://newpodcast2.vercel.app/api/songs');
  const songsdata = await songs.json();
  const data = await res.json();


  return {
    props: {
      products: data,
      songs: songsdata,
    }
  }
}



